// Next
import type { Metadata } from "next";
import { Didact_Gothic, JetBrains_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";

// Css
import "./globals.css";

// Local
import Navbar from "@/app/navbar";

// Fonts
const didact_gothic = Didact_Gothic({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-didact-gothic",
});
const jetbrains_mono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${didact_gothic.variable} ${jetbrains_mono.variable}`}
    >
      <body className="h-screen flex flex-col bg-primary text-complementary dark:bg-primaryDark dark:text-complementaryDark">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
